apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: dr-sim-aws-secrets
spec:
  provider: aws
  parameters:
    usePodIdentity: "true"
    objects: |
      - objectName: "primary-rds-credentials"
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "DB_USERNAME"
          - path: "password"
            objectAlias: "DB_PASSWORD"
          - path: "host"
            objectAlias: "DB_HOST"
          - path: "port"
            objectAlias: "DB_PORT"
          - path: "db_name"
            objectAlias: "DB_NAME"
  secretObjects:
    - secretName: db-credentials
      type: Opaque
      data:
        - key: DB_USERNAME
          objectName: DB_USERNAME
        - key: DB_PASSWORD
          objectName: DB_PASSWORD
        - key: DB_HOST
          objectName: DB_HOST
        - key: DB_PORT
          objectName: DB_PORT
        - key: DB_NAME
          objectName: DB_NAME
